name: Deploy Repo via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH connection and update repository
        run: |
          # Ensure private key permissions are set correctly
          $PrivateKeyPath = "C:\ssh_private_key.pem"
          Set-Content -Path $PrivateKeyPath -Value "${{ secrets.STW2_KEY }}"
         
          # Use SSH to connect and update the repository
          $sshCommand = @"
          cd ${{ secrets.STW2_FILE_PATH }}
          git pull
          "@
          ssh -o StrictHostKeyChecking=no -i $PrivateKeyPath ${{ secrets.STW2_USER }}@${{ secrets.STW2_IP }} "$sshCommand"
        shell: pwsh
