name: Testing CI/CD to STW2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-local-repo:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Native Windows SSH Agent
      run: |
        echo "Starting SSH agent..."
        ssh-agent -k
        ssh-add -L || echo "No identities added. Trying to add default key..."
        echo "Adding SSH key to the agent..."
        echo "${{ secrets.STW2_KEY }}" > ssh_key.pem
        ssh-add ssh_key.pem || echo "No default key found."

    - name: List SSH 
      run: |
        echo "Checking SSH Agent Identities..."
        ssh-add -L

    - name: Update Local Repo
      run: |
        $serverAddress = "${{ secrets.STW2_IP }}"
        $serverUser = "${{ secrets.STW2_USER }}"
        $localRepoPath = '${{ secrets.STW2_FILE_PATH }}'
        
        # Log server details for debugging
        Write-Host "Server Address: $serverAddress"
        Write-Host "Server User: $serverUser"
        Write-Host "Local Repo Path: $localRepoPath"
        
        # Log SSH command
        $sshCommand = "ssh -v $serverUser@$serverAddress 'cd $localRepoPath && git pull origin main'"
        Write-Host "Running SSH command: $sshCommand"
    
        # Run SSH command
        Invoke-Expression -Command $sshCommand

        Write-Host "Clossing SSH Session"
        exit
        
        
