name: Testing CI/CD to STW2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-local-repo:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.STW2_KEY }}

    # - name: Use SSH key
    #   uses: actions/setup-ssh@v2
    #   with:
    #     ssh-private-key: ${{ secrets.STW2_KEY }}

    - name: Update Local Repo
      run: |
        $serverAddress = "${{ secrets.STW2_IP }}"
        $serverUser = "${{ secrets.STW2_USER }}"
        $localRepoPath = '${{ secrets.STW2_FILE_PATH }}'
        
        # Log server details for debugging
        Write-Host "Server Address: $serverAddress"
        Write-Host "Server User: $serverUser"
        Write-Host "Local Repo Path: $localRepoPath"
        
        # Log SSH command
        $sshCommand = ssh $serverUser@$serverAddress "cd $localRepoPath && git pull origin main"
        Write-Host "Running SSH command: $sshCommand"
    
        # Run SSH command
        Invoke-Expression -Command $sshCommand
        
        
